const GET_USERS = "GET_USERS";
const GET_PRODUCTS = "GET_PRODUCTS";
const FILTER_PRODUCTS_BY_CATEGORY = "FILTER_PRODUCTS_BY_CATEGORY";
const GET_PRODUCT_BY_NAME = "GET_PRODUCT_BY_NAME";
const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
const DELETE_PRODUCT_BY_ID = "DELETE_PRODUCT_BY_ID";
const FILTER_PRODUCT_BY_PRICE = "FILTER_PRODUCT_BY_PRICE";
const CREATE_REVIEW = 'CREATE_REVIEW';
const SIGNUP = "SIGNUP";
const LOGOUT = "LOGOUT";
const LOGIN = "LOGIN";
const ACTIVE_PRODUCTS_NAME = "ACTIVE_PRODUCTS_NAME";
const ACTIVE_PRODUCTS_PRICE = "ACTIVE_PRODUCTS_PRICE";
const ACTIVE_PRODUCTS_CATEGORY = "ACTIVE_PRODUCTS_CATEGORY";
const FILTER_PRODUCTS = "FILTER_PRODUCTS";
const ADD_TO_CART = "ADD_TO_CART";
const CREATE_ORDER = "CREATE_ORDER";
const FILTER_PRODUCTS_BY_TYPE = "FILTER_PRODUCTS_BY_TYPE";
const FILTER_PRODUCTS_BY_GENDER = "FILTER_PRODUCTS_BY_GENDER";
const ACTIVE_PRODUCTS_PLATFORM = "ACTIVE_PRODUCTS_PLATFORM";
const DECREASE_CART = "DECREASE_CART";
const INCREASE_CART = "INCREASE_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const RESTART_CART = "RESTART_CART";
const LOGIN_GOOGLE = "LOGIN_GOOGLE";
// const RESTART_CART = "RESTART_CART";
const CREATE_PRODUCT = "CREATE_PRODUCT";
const MODIFY_STOCK_PRODUCT = "MODIFY_STOCK_PRODUCT";
const LOADINGFORM = "LOADINGFORM"
const ERROR_LOGIN = "ERROR_LOGIN"
const CLEAR_ERRORS = "CLEAR_ERRORS"
const GET_ORDERS = "GET_ORDERS";
const UPDATE_USER = "UPDATE_USER";
const ERROR_REGISTER = "ERROR_REGISTER"
const ADD_FAVORITE = "ADD_FAVORITE";
const REMOVE_FAVORITE = "REMOVE_FAVORITE";

const GET_USER_PRODUCTS = "GET_USER_PRODUCTS"
const GET_NOT_REVIEW = "GET_NOT_REVIEW"
const OPEN_EDIT = "OPEN_EDIT_REVIEW"
const EDIT_REVIEW = "EDIT_REVIEW"
module.exports = {
  GET_USERS,
  GET_ORDERS,
  MODIFY_STOCK_PRODUCT,
  GET_USER_PRODUCTS,
  UPDATE_USER,
  CREATE_REVIEW,
  GET_PRODUCTS,
  FILTER_PRODUCTS_BY_CATEGORY,
  FILTER_PRODUCTS_BY_GENDER,
  GET_PRODUCT_BY_NAME,
  GET_PRODUCT_BY_ID,
  DELETE_PRODUCT_BY_ID,
  FILTER_PRODUCT_BY_PRICE,
  SIGNUP,
  LOGOUT,
  ACTIVE_PRODUCTS_PLATFORM,
  LOGIN,
  ADD_TO_CART,
  FILTER_PRODUCTS,
  CREATE_ORDER,
  FILTER_PRODUCTS_BY_TYPE,
  DECREASE_CART,
  ACTIVE_PRODUCTS_PRICE,
  INCREASE_CART,
  ACTIVE_PRODUCTS_CATEGORY,
  REMOVE_FROM_CART,
  RESTART_CART,
  LOGIN_GOOGLE,
  // RESTART_CART,
  CREATE_PRODUCT,
  ACTIVE_PRODUCTS_NAME,
  LOADINGFORM,
  ERROR_LOGIN,
  CLEAR_ERRORS,
  ERROR_REGISTER,

  GET_NOT_REVIEW,
  OPEN_EDIT,
  EDIT_REVIEW,

  ADD_FAVORITE,
  REMOVE_FAVORITE

};
