const GET_USERS = "GET_USERS";
const GET_PRODUCTS = "GET_PRODUCTS";
const FILTER_PRODUCTS_BY_CATEGORY = "FILTER_PRODUCTS_BY_CATEGORY";
const GET_PRODUCT_BY_NAME = "GET_PRODUCT_BY_NAME";
const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
const DELETE_PRODUCT_BY_ID = "DELETE_PRODUCT_BY_ID";
const FILTER_PRODUCT_BY_PRICE = "FILTER_PRODUCT_BY_PRICE";
const SIGNUP = "SIGNUP";
const LOGOUT = "LOGOUT";
const LOGIN = "LOGIN";
const FILTER_PRODUCTS = "FILTER_PRODUCTS";
const ADD_TO_CART = "ADD_TO_CART";
const CREATE_ORDER = "CREATE_ORDER";
const FILTER_PRODUCTS_BY_TYPE = "FILTER_PRODUCTS_BY_TYPE";
const FILTER_PRODUCTS_BY_GENDER = "FILTER_PRODUCTS_BY_GENDER";
const DECREASE_CART = "DECREASE_CART";
const INCREASE_CART = "INCREASE_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";

module.exports = {
  GET_USERS,
  GET_PRODUCTS,
  FILTER_PRODUCTS_BY_CATEGORY,
  FILTER_PRODUCTS_BY_GENDER,
  GET_PRODUCT_BY_NAME,
  GET_PRODUCT_BY_ID,
  DELETE_PRODUCT_BY_ID,
  FILTER_PRODUCT_BY_PRICE,
  SIGNUP,
  LOGOUT,
  LOGIN,
  ADD_TO_CART,
  FILTER_PRODUCTS,
  CREATE_ORDER,
  FILTER_PRODUCTS_BY_TYPE,
  DECREASE_CART,
  INCREASE_CART,
  REMOVE_FROM_CART,
};
