const GET_USERS = "GET_USERS";
const GET_PRODUCTS = "GET_PRODUCTS";
const FILTER_PRODUCTS_BY_CATEGORY = "FILTER_PRODUCTS_BY_CATEGORY";
const GET_PRODUCT_BY_NAME = "GET_PRODUCT_BY_NAME";
const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID"

module.exports = {
    GET_USERS,
    GET_PRODUCTS,
    FILTER_PRODUCTS_BY_CATEGORY,
    GET_PRODUCT_BY_NAME,
    GET_PRODUCT_BY_ID,
}
